agentless-config
kubecost/poc-common-configurations pull request #105
Opened 2024-02-20 20:40 UTC by jessegoodier

2024-03-05 00:32 UTC, srpomeroy requested changes
Looks good Jesse! I definitely want to have a conversation with you around ADOT/agentless.

2024-03-05 00:32 UTC, srpomeroy commented on aws-amp/agentless/README.md
> +  WORKSPACE_ARN=$(aws amp describe-workspace --workspace-id ws-a8c57716-3efb-4fab-ab90-13e6be2a0280 --output json | jq -r .workspace.arn)
We should replace the workspace ID with a fake value.

2024-03-05 00:32 UTC, srpomeroy commented on aws-amp/agentless/README.md
> +  WORKSPACE_ID=ws-a8c57716-3efb-4fab-ab90-13e6be2a0280
Not used. Should not contain an actual workspace id.

2024-03-06 12:47 UTC, jessegoodier commented
good finds!
Going to reorganize this whole thing, but already updated with what you found.

2024-04-02 12:57 UTC, merged